{{- if .Values.installCRDs }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devenvs.anareta.dev
spec:
  group: anareta.dev
  names:
    plural: devenvs
    singular: devenv
    kind: DevEnv
    shortNames:
      - devenv
      - devs
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - repoURL
                - branch
              properties:
                repoURL:
                  type: string
                branch:
                  type: string
                ttl:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
                startedAt:
                  type: string
      subresources:
        status: {}
{{- end }}
