{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
rules:
  - apiGroups:   ["anareta.dev"]
    resources:   ["devenvs"]
    verbs:       ["get","list","watch","create","update","patch","delete"]
{{- end }}
