apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-metrics
  labels:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.servicePort }}
      targetPort: metrics
    - name: webhook
      port: {{ .Values.webhook.servicePort }}
      targetPort: webhook
  selector:
    app: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
