apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anareta-operator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: anareta-operator
    namespace: default
roleRef:
  kind: Role
  name: anareta-operator-role
  apiGroup: rbac.authorization.k8s.io
